---
- hosts: localhost
  connection: local

  tasks:
  - name: Install packages
    yum:
      name:
        - qemu-kvm
        - libvirt
        - libvirt-python
        - libguestfs-tools
        - virt-install
      state: present
      update_cache: yes

  - name: Enable and start libvirtd service
    service:
      name: libvirtd
      state: started
      enabled: yes

  - name: Uncomment root user in qemu config
    lineinfile:
      path: /etc/libvirt/qemu.conf
      regexp: '^#user = "root"'
      line: user = root

  - name: Uncomment root user in qemu config
    lineinfile:
      path: /etc/libvirt/qemu.conf
      regexp: '^#group = "root"'
      line: group = root

  - name: Copy bridge configuration
    copy:
      src: files/ifcfg-br0
      dest: /etc/sysconfig/network-scripts/ifcfg-br0

  - name: Edit /etc/sysconfig/network-scripts/ifcfg-enp0s3 to include the bridge
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-enp0s3
      insertafter: EOF
      line: BRIDGE=br0

  - name: Enable netowrk forwarding
    lineinfile:
      path: /etc/sysctl.conf
      insertafter: EOF
      line: 'net.ipv4.ip_forward = 1'

  - name: Load the netowkr configuration
    shell: sysctl -p /etc/sysctl.conf

  - name: Restart Network Manager
    service:
      name: NetworkManager
      state: restarted