- name: Create a virtual machine from a template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: /"{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: "{{ vm_state }}"
    template: "{{ vm_template }}"
    disk:
    - size_gb: 40
      type: thin
      datastore: "{{ datastore }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ cpu_count }}"
      num_cpu_cores_per_socket: 2
      scsi: paravirtual
      hotadd_cpu: True
      hotadd_memory: False
      version: 12 # Hardware version of virtual machine
      boot_firmware: "efi"
    networks:
    - name: "{{ vm_network }}"
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy
